version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: deuseli
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306